snapshot:
  name_template: SNAPSHOT-{{.Commit}}

builds:
  - main: cmd/jocko/main.go
    binary: jocko
    goos:
      - darwin
      - linux
    goarch:
      - amd64

brew:
  github:
    owner: nash-io
    name: homebrew-tap

  commit_author:
    name: Fabio C Canesin
    email: canesin@nash.io

  folder: Formula

  homepage: "https://github.com/nash-io"

  description: "Kafka implemented in Golang with built-in coordination (No ZK dep, single binary install)"

